import { StyleSheet } from "react-native";
import EkranLogowania from "./index";


export const styles = StyleSheet.create({
    ekranLogowania: {
        position: "relative",
        backgroundColor: '#000',
        flex: 1,
        width: "100%",
        height: 896,
        overflow: "hidden",
    },
    backgroundImage: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        resizeMode: 'cover',
        backgroundColor: '#000',
    },
    frameChild: {
        position: "absolute",
        top: 0,
        left: 0,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameItem: {
        position: "absolute",
        top: 0,
        left: 518,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameInner: {
        position: "absolute",
        top: 0,
        left: 1036,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    rectangleLineargradient: {
        position: "absolute",
        top: 0,
        left: 75,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild1: {
        position: "absolute",
        top: 0,
        left: 593,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild2: {
        position: "absolute",
        top: 0,
        left: 1111,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild3: {
        position: "absolute",
        top: 0,
        left: 149,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild4: {
        position: "absolute",
        top: 0,
        left: 667,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild5: {
        position: "absolute",
        top: 0,
        left: 1185,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild6: {
        position: "absolute",
        top: 0,
        left: 224,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild7: {
        position: "absolute",
        top: 0,
        left: 742,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild8: {
        position: "absolute",
        top: 0,
        left: 1260,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild9: {
        position: "absolute",
        top: 0,
        left: 298,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild10: {
        position: "absolute",
        top: 0,
        left: 816,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild11: {
        position: "absolute",
        top: 0,
        left: 373,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild12: {
        position: "absolute",
        top: 0,
        left: 891,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild13: {
        position: "absolute",
        top: 0,
        left: 1409,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild14: {
        position: "absolute",
        top: 0,
        left: 1558,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild15: {
        position: "absolute",
        top: 0,
        left: 1632,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild16: {
        position: "absolute",
        top: 0,
        left: 1483,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild17: {
        position: "absolute",
        top: 0,
        left: 447,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild18: {
        position: "absolute",
        top: 0,
        left: 1334,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    frameChild19: {
        position: "absolute",
        top: 0,
        left: 965,
        width: 75,
        height: 949,
        backgroundColor: "transparent",
    },
    rectangleParent: {
        position: "relative",
        width: 1707,
        height: 949,
    },
    frame1: {
        position: "absolute",
        top: 0,
        left: 0,
        width: 2057,
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "flex-end",
        justifyContent: "center",
    },
    frameIcon: {
        position: "absolute",
        top: 23,
        left: 822,
        width: 914,
        height: 895,
        overflow: "hidden",
    },
    frameIcon1: {
        position: "absolute",
        top: 23,
        left: 822,
        width: 1014,
        height: 895,
        overflow: "hidden",
    },
    witaj: {
        alignSelf: "stretch",
        position: "relative",
        fontSize: 40,
        fontWeight: "500",
        color: 'white',
        textAlign: "left",
    },
    ponownie: {
        alignSelf: "stretch",
        position: "relative",
        fontSize: 63,
        fontWeight: "600",
        color: 'white',
        textAlign: "left",
        marginTop: -17,
    },
    appName: {
        alignSelf: "stretch",
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "center",
        paddingHorizontal: 0,
        paddingVertical: 5,
    },
    appNameWrapper: {
        alignSelf: "stretch",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "center",
    },
    frame2: {
        position: "absolute",
        top: 160,
        left: 865,
        width: 328,
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "center",
    },
    adresEmail: {
        position: "relative",
        fontSize: 22,
        lineHeight: 20,
        fontWeight: "500",
        color: 'white',
        textAlign: "left",
        width: 238,
    },
    emailicon: {
        position: "relative",
        width: 24,
        height: 24,
        overflow: "hidden",
        marginLeft: 18,
    },
    frame4: {
        width: 280,
        height: 24,
        overflow: "hidden",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    fieldChild: {
        position: "relative",
        width: 295,
        height: 1,
        marginTop: 14,
    },
    field: {
        width: 295,
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-end",
        paddingTop: 4,
    },
    field1: {
        width: 295,
        height: 52,
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-end",
        paddingTop: 4,
        marginTop: 23,
    },
    fieldParent: {
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-start",
    },
    frameView: {
        alignSelf: "stretch",
        height: 152,
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        padding: 10,
    },
    frame3: {
        position: "absolute",
        top: 437,
        left: 871,
        width: 316,
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    text: {
        flex: 1,
        position: "relative",
        fontSize: 19,
        color: 'white',
        textAlign: "left",
        display: "flex",
        alignItems: "center",
        height: 20,
    },
    signalIcon: {
        position: "relative",
        width: 18,
        height: 18,
    },
    wiFiIcon: {
        position: "relative",
        width: 24,
        height: 22,
        marginLeft: 6,
    },
    fullBatteryIcon: {
        position: "relative",
        width: 29,
        height: 32,
        marginLeft: 6,
    },
    signalParent: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        marginLeft: 226,
    },
    iphonestatusbar: {
        position: "absolute",
        marginLeft: -176,
        top: 28,
        left: "50%",
        width: 343,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    frame: {
        position: "absolute",
        top: -23,
        left: -822,
        width: 2057,
        height: 949,
        overflow: "hidden",
    },
    startLearning: {
        position: "relative",
        fontSize: 40,
        letterSpacing: 0.6,
        lineHeight: 29,
        fontWeight: "500",
        color: 'black',
        textAlign: "left",
    },
    vectorIcon: {
        position: "relative",
        width: 22,
        height: 14,
        marginLeft: 10,
    },
    button: {
        borderRadius: 6,
        backgroundColor: 'white',
        width: 329,
        overflow: "hidden",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 62,
        paddingVertical: 24,
        height: 75,
        marginLeft: 1,
    },
    buttonText: {
        color: 'black',
        fontSize: 20,
       // fontFamily: 'Poppins-Medium',
        fontWeight: '500',
        lineHeight: 28.64,
        letterSpacing: 0.63,
    },
    niePosiadaszKonta: {
        position: "relative",
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "500",
        color: 'white',
        textAlign: "center",
        width: 260,
        marginTop: 27,
    },
    frame7: {
        width: 330,
        height: 122,
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    line: {
        position: "relative",
        borderRadius: 575,
        backgroundColor: 'white',
        width: 169,
        height: 5,
    },
    iphoneIndicator: {
        backgroundColor: "rgba(4, 4, 4, 0.33)",
        width: 430,
        height: 32,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 101,
        paddingVertical: 48,
        marginTop: 88,
    },
    frame6: {
        position: "absolute",
        top: 654,
        left: -8,
        width: 430,
        height: 242,
        overflow: "hidden",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
    }
});

