/* fonts */
import {StyleSheet} from "react-native";

export const FontFamily = {
  berlinSansFB: "Berlin Sans FB",
  poppinsBold: "Poppins-Bold",
  poppinsSemiBold: "Poppins-SemiBold",
  poppinsMedium: "Poppins-Medium",
};
/* font sizes */
export const FontSize = {
  size_lg: 18,
  size_3xl: 22,
  size_mid: 17,
  size_7xs: 6,
};
/* Colors */
export const Color = {
  colorBlack: "#000",
  colorWhite: "#fff",
  colorWhitesmoke_100: "#ececec",
  colorGray_100: "#0c0c0c",
  colorGray_200: "rgba(255, 255, 255, 0.1)",
  colorLightgray: "#cbcbcb",
};
/* Paddings */
export const Padding = {
  p_8xs: 5,
};
/* border radiuses */
export const Border = {
  br_16xl: 35,
  br_xl: 20,
  br_11xl: 30,
};

export const styles = StyleSheet.create({
  wzrLayout: {
    height: 896,
    backgroundColor: Color.colorBlack,
    overflow: "hidden",
  },
  textTypo: {
    fontFamily: FontFamily.poppinsSemiBold,
    fontWeight: "600",
  },
  sliderItemPosition: {
    left: 21,
    position: "absolute",
  },
  groupParentFlexBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  garyTypo: {
    marginLeft: 21,
    color: Color.colorGray_100,
    lineHeight: 26,
    height: 26,
    textAlign: "left",
    fontSize: FontSize.size_mid,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
  },
  textFlexBox: {
    display: "flex",
    alignItems: "center",
  },
  sliderLayout: {
    height: 186,
    width: 578,
    position: "absolute",
  },
  image2IconPosition: {
    height: 184,
    left: 0,
    top: 0,
  },
  sliderBg: {
    backgroundColor: "transparent",
    position: "absolute",
  },
  frameFlexBox: {
    height: 73,
    alignItems: "center",
    flexDirection: "row",
  },
  appSpaceBlock: {
    height: 106,
    paddingVertical: Padding.p_8xs,
    paddingHorizontal: 0,
    justifyContent: "center",
    overflow: "hidden",
  },
  iconLayout: {
    height: 35,
    width: 35,
  },
  navigationBarPosition: {
    width: 430,
    bottom: 0,
    position: "absolute",
  },
  duyParentLayout: {
    width: 341,
    backgroundColor: Color.colorGray_200,
    borderRadius: Border.br_16xl,
    height: 109,
    overflow: "hidden",
  },
  duyTypo: {
    fontSize: FontSize.size_3xl,
    top: 27,
    display: "flex",
    color: Color.colorLightgray,
    left: "50%",
    textAlign: "left",
    alignItems: "center",
    fontFamily: FontFamily.poppinsSemiBold,
    fontWeight: "600",
    position: "absolute",
  },
  zTypo: {
    fontFamily: FontFamily.poppinsBold,
    fontWeight: "700",
    fontSize: FontSize.size_lg,
    textAlign: "left",
    position: "absolute",
  },
  parentPosition: {
    left: 31,
    position: "absolute",
  },
  twojeZamwienieJest: {
    fontSize: 32,
    height: 53,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    textAlign: "center",
    color: Color.colorWhite,
    width: 322,
  },
  appName: {
    height: 151,
    paddingVertical: Padding.p_8xs,
    paddingHorizontal: 0,
    justifyContent: "center",
    overflow: "hidden",
  },
  appNameWrapper: {
    height: 103,
    justifyContent: "center",
    left: 0,
    top: 0,
    position: "absolute",
  },
  przetwarzane: {
    top: 127,
    fontSize: 40,
    height: 86,
    textAlign: "center",
    fontWeight: "600",
    color: Color.colorWhite,
    left: 0,
    width: 322,
    position: "absolute",
  },
  frameParent: {
    top: 356,
    left: 42,
    height: 213,
    width: 322,
    position: "absolute",
  },
  frameChild: {
    borderRadius: Border.br_xl,
    width: 370,
    height: 89,
    zIndex: 0,
    backgroundColor: Color.colorWhite,
  },
  maskGroupIcon: {
    width: 40,
    height: 40,
  },
  garyLee: {
    width: 259,
  },
  maskGroupParent: {
    top: 22,
    zIndex: 1,
    alignItems: "center",
    left: 31,
    position: "absolute",
  },
  rectangleParent: {
    top: 648,
  },
  wzrChild: {
    top: 116,
    left: 53,
    width: 269,
    height: 240,
    position: "absolute",
  },
  zazwyczajZamwieniaPrzetwarz: {
    marginLeft: -155,
    top: 552,
    fontSize: 15,
    width: 311,
    color: Color.colorLightgray,
    display: "flex",
    left: "50%",
    textAlign: "center",
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    justifyContent: "center",
    position: "absolute",
  },
  image2Icon: {
    width: 434,
    position: "absolute",
  },
  sliderChild: {
    height: 184,
    left: 0,
    top: 0,
    width: 578,
    backgroundColor: "transparent",
  },
  sliderItem: {
    width: 367,
    height: 40,
    top: 0,
  },
  sliderInner: {
    top: 121,
    left: 1,
    width: 375,
    height: 65,
  },
  slider: {
    left: 0,
    top: 0,
  },
  twojeKonto: {
    color: Color.colorWhitesmoke_100,
    textAlign: "left",
    fontSize: FontSize.size_mid,
    height: 53,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    width: 322,
  },
  zamwienie: {
    fontSize: 33,
    marginTop: -29,
    color: Color.colorWhitesmoke_100,
    textAlign: "left",
    width: 322,
  },
  appName1: {
    width: 267,
  },
  appNameContainer: {
    width: 258,
    height: 111,
    justifyContent: "center",
  },
  frameWrapper: {
    width: 158,
  },
  maskGroupChild: {
    height: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    maxWidth: "100%",
    maxHeight: "100%",
    position: "absolute",
    overflow: "hidden",
    width: "100%",
  },
  maskGroupItem: {
    top: 10,
    left: 8,
    width: 26,
    height: 13,
    position: "absolute",
  },
  maskGroupInner: {
    top: 16,
    left: 25,
    width: 9,
    height: 9,
    position: "absolute",
  },
  text: {
    marginTop: -0.5,
    marginLeft: 10.5,
    top: "50%",
    fontSize: FontSize.size_7xs,
    width: 3,
    height: 7,
    left: "50%",
    textAlign: "left",
    fontFamily: FontFamily.poppinsSemiBold,
    fontWeight: "600",
    display: "flex",
    color: Color.colorWhite,
    position: "absolute",
  },
  maskGroup: {
    left: 0,
    top: 0,
    position: "absolute",
  },
  koszyk: {
    top: 8,
    left: 0,
    position: "absolute",
  },
  frameItem: {
    width: 55,
    height: 55,
  },
  vectorWrapper: {
    top: -4,
    left: 51,
    borderRadius: 50,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderWidth: 4,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
  },
  koszykParent: {
    width: 110,
    marginLeft: 82,
    height: 55,
  },
  frameGroup: {
    top: 58,
    left: 29,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
  },
  headerEkranuPrzeksek: {
    top: 21,
    left: 3,
  },
  popcornactiveIcon: {
    marginLeft: 58,
  },
  homeinactiveParent: {
    top: 18,
    width: 368,
    height: 58,
    alignItems: "center",
    left: 31,
    position: "absolute",
    justifyContent: "center",
  },
  navigationBarChild: {
    top: 17,
    left: 140,
    borderRadius: 13,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    width: 58,
    height: 59,
    position: "absolute",
    overflow: "hidden",
  },
  line: {
    borderRadius: 575,
    width: 169,
    height: 5,
    backgroundColor: Color.colorWhite,
  },
  iphoneIndicator: {
    paddingHorizontal: 101,
    paddingVertical: 48,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    left: 0,
  },
  navigationBar: {
    marginLeft: -215,
    borderBottomRightRadius: Border.br_11xl,
    borderBottomLeftRadius: Border.br_11xl,
    backgroundColor: "#141414",
    height: 142,
    left: "50%",
    overflow: "hidden",
  },
  backIcon: {
    width: 30,
    height: 30,
  },
  zamwienie1: {
    color: Color.colorWhitesmoke_100,
    height: 26,
    textAlign: "left",
    fontSize: FontSize.size_mid,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    width: 322,
  },
  ustawieniaKonta: {
    fontSize: 30,
    lineHeight: 77,
    width: 171,
    marginTop: -22,
    height: 55,
    color: Color.colorWhitesmoke_100,
    textAlign: "left",
  },
  appName2: {
    width: 278,
  },
  appNameFrame: {
    width: 235,
    height: 66,
    justifyContent: "center",
  },
  frameContainer: {
    marginLeft: 17,
    width: 278,
  },
  backParent: {
    top: 205,
    left: 63,
    width: 294,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
  },
  garyLee1: {
    width: 182,
  },
  duyPopcorn: {
    marginLeft: -32.5,
    width: 203,
  },
  z: {
    top: 64,
    marginLeft: 26.5,
    fontFamily: FontFamily.poppinsBold,
    fontWeight: "700",
    fontSize: FontSize.size_lg,
    color: Color.colorLightgray,
    left: "50%",
  },
  closeUpDeliciousSaltedPopcIcon: {
    width: 70,
    height: 101,
    top: 0,
  },
  duyPopcornParent: {
    height: 109,
  },
  duyNapj: {
    marginLeft: -25.5,
    width: 196,
  },
  z1: {
    display: "none",
    top: 64,
    marginLeft: 26.5,
    fontFamily: FontFamily.poppinsBold,
    fontWeight: "700",
    fontSize: FontSize.size_lg,
    color: Color.colorLightgray,
    left: "50%",
  },
  image28Icon: {
    top: 7,
    left: 13,
    width: 111,
    height: 109,
    position: "absolute",
  },
  duyNapjParent: {
    marginTop: 20,
    height: 109,
  },
  zestaw: {
    top: 289,
    left: 36,
    position: "absolute",
  },
  wzrItem: {
    top: 555,
    left: 43,
    width: 327,
    height: 0,
    position: "absolute",
  },
  z3: {
    textDecoration: "line-through",
    color: "rgba(236, 236, 236, 0.5)",
  },
  z4: {
    color: Color.colorWhitesmoke_100,
  },
  z25Z: {
    top: 561,
    left: 318,
  },
  doZapaty: {
    top: 566,
    left: 45,
    color: Color.colorWhitesmoke_100,
  },
  text1: {
    fontSize: 19,
    fontFamily: FontFamily.berlinSansFB,
    width: 43,
    height: 20,
    textAlign: "left",
    display: "flex",
    color: Color.colorWhite,
  },
  signalIcon: {
    width: 18,
    height: 18,
  },
  wiFiIcon: {
    width: 24,
    height: 22,
    marginLeft: 6,
  },
  fullBatteryIcon: {
    width: 29,
    marginLeft: 6,
    height: 32,
  },
  signalParent: {
    marginLeft: 226,
    alignItems: "center",
  },
  iphonestatusbar: {
    marginLeft: -176,
    top: 5,
    left: "50%",
    alignItems: "center",
    position: "absolute",
  },
  wzr1: {
    top: -1846,
    left: -1047,
    borderRadius: 40,
    width: 414,
    position: "absolute",
    overflow: "hidden",
  },
  wzr: {
    flex: 1,
    overflow: "hidden",
    width: "100%",
  },
});
